services:
  db:
    image: postgres:16.6
    container_name: fs_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flat_scraper_network

volumes:
  postgres_data:

networks:
  flat_scraper_network:
    driver: bridge