services:
  db:
    image: postgres
    container_name: fs_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flat_scraper_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flat_scraper_network

volumes:
  postgres_data:

networks:
  flat_scraper_network:
    driver: bridge