services:
  db:
    image: postgres
    container_name: fs_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flat_scraper_network

volumes:
  postgres_data:

networks:
  flat_scraper_network:
    driver: bridge